### ISSUE TITLE
wrong graph

### ISSUE THREAD

**Issue by dieterdreist** [Gustavo22Soaresh/osm-comunity-survey#1]
Please update the graph for:
Corporate and bot profiles should be easy to recognize

**Comment by Gustavo22Soaresh** [comment]
thanks, itś already fixed

**Comment by dieterdreist** [comment]
hi, I still see the wrong graph:

![Screenshot 2024-12-02 at 21 19 27](https://github.com/user-attachments/assets/c647801f-4f41-4a91-b949-1643c03879f7)

**Comment by Gustavo22Soaresh** [comment]
Do you have try to refresh your cache??
![image](https://github.com/user-attachments/assets/00bc5c74-7439-49dd-91df-93fcb798ab9e)

**Comment by dieterdreist** [comment]
Some hours ago I saw it here: https://github.com/Gustavo22Soaresh/osm-comunity-survey/blob/main/2024/results.pdf

now its fixed, thank you
